include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_empty_else: true
    prefer_const_constructors: true
    prefer_final_fields: true
    always_declare_return_types: true
    avoid_returning_null_for_void: true
