#include <flutter/dart_project.h>
#include <flutter/flutter_view_controller.h>
#include <windows.h>
#include "utils.h"

// Minimal Windows runner entry point placeholder.
// Use `flutter build windows` or `flutter run -d windows` to generate the full runner.

int APIENTRY wWinMain(HINSTANCE instance, HINSTANCE prev, LPWSTR cmd, int show_command) {
  // Initialize and run the Flutter view controller (actual implementation generated by Flutter).
  MessageBox(NULL, L"Adlik Flutter (Windows) runner placeholder. Use flutter run to generate native runner.", L"Adlik", MB_OK);
  return 0;
}
